In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score, RepeatedStratifiedKFold
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into a train and test split (70% and 30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a simple Perceptron model with learning rate (eta0) as 0.0001 and 50 epochs
perceptron = Perceptron(eta0=0.0001, max_iter=50, random_state=42)
perceptron.fit(X_train, y_train)

# Make predictions on the test set
y_pred = perceptron.predict(X_test)

# Calculate performance measures
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
confusion = confusion_matrix(y_test, y_pred)

# Print the performance measures for 50 epochs
print("Performance Measures for 50 Epochs:")
print("Accuracy Score:", accuracy)
print("Precision Score:", precision)
print("Recall Score:", recall)
print("Confusion Matrix:")
print(confusion)

# Evaluate the model with different epoch values from 100 to 1000
epoch_values = list(range(100, 1100, 100))
for epochs in epoch_values:
    perceptron = Perceptron(eta0=0.0001, max_iter=epochs, random_state=42)
    perceptron.fit(X_train, y_train)
    y_pred = perceptron.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\nPerformance Measures for {epochs} Epochs:")
    print("Accuracy Score:", accuracy)

# Evaluate the model using repeated stratified k-fold cross-validation
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=42)
scores = cross_val_score(perceptron, X, y, scoring='accuracy', cv=cv)
print("\nPerformance Measures with Repeated Stratified K-Fold Cross-Validation:")
print("Mean Accuracy:", np.mean(scores))


Performance Measures for 50 Epochs:
Accuracy Score: 0.8666666666666667
Precision Score: 0.8918145035792093
Recall Score: 0.8666666666666667
Confusion Matrix:
[[19  0  0]
 [ 2  7  4]
 [ 0  0 13]]

Performance Measures for 100 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 200 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 300 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 400 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 500 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 600 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 700 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 800 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 900 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures for 1000 Epochs:
Accuracy Score: 0.8666666666666667

Performance Measures with Repeated Stratified K-Fold Cross-Validation:
Me